name: Build Ingestion Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'ingest.dockerfile'
      - 'ingest/**/*.py'
      - 'ingest/requirements.txt'

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to publish (defaults to 'latest')"
        required: false
        default: latest
        type: string

env:
  REGISTRY: docker.io
  IMAGE_REPO: aaalexlit/zoomcamp-faq-ingest
  IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}

jobs:
  build-and-push:
    name: Build → Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write       # required for provenance attestation (optional)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Compute short git SHA
        id: gitsha
        run: echo "sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ingest/ingest.dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ steps.gitsha.outputs.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:latest
          cache-from: type=gha
          cache-to:   type=gha,mode=max
